/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BanHang_HoaDon;

import Controller.*;
import com.itextpdf.text.DocumentException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.SanPham;
import helper.ShareData;
/**
 *
 * @author trieu
 */
public class Ban_Hang extends javax.swing.JPanel {

    //Hoa_Don hd = new Hoa_Don();
    check_input check = new check_input();
    ChucNangKhac chucNangKhac = new ChucNangKhac();
    DAO d = new DAO();
    
    //SanPham sp = new SanPham();
    public Ban_Hang() {
        initComponents();
        tableSanPham.setRowHeight(35);
        
        txtNhanVien.setText(ShareData.taikhoandangnhap.getMaNV());
        tableDonHang.setRowHeight(35);
        
        d.LoadTable_SP(tableSanPham,"Mới");
        d.Load_to_InFohachHang(tableInfoKH);

        //popmenuEmei.add(panelEmei); // để khỏi thêm nhiều lần
//        popmenuMaGiamGia.add(panelMaGiamGia);  // để khỏi thêm nhiều lần
        jPopupMenu1.add(scrollInfoKH);
        //DefaultTableModel model=(DefaultTableModel) tableDonHang.getModel();/      
        //model.setRowCount(0);
        //d.add_Col_DonHang(tableDonHang);
        // COi lại chỗ này vì chưa đúng liên quan đến rows
        //tableDonHang.removeEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGDiaChiNhanHang = new javax.swing.ButtonGroup();
        btnGTrangThaiGH = new javax.swing.ButtonGroup();
        scrollInfoKH = new javax.swing.JScrollPane();
        tableInfoKH = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane5 = new javax.swing.JScrollPane();
        listEmei = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtSearchSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbbPhanLoaiSP = new javax.swing.JComboBox<>();
        btnGiam = new javax.swing.JButton();
        btnTang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panelSanPham = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        panelDonHang = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDonHang = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        panelThongTinKH = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAGhiChu = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        rbtnTaiCuaHang = new javax.swing.JRadioButton();
        rbtnTaiNha = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtADiaChiNhanHang = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        txtPhiVanChuyen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbtnDangGiaoHang = new javax.swing.JRadioButton();
        rbtnChuaGiaoHang = new javax.swing.JRadioButton();
        rbtnDaGiao = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtKhachDua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbbChonMaGiamGia = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtTongTienHang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtKhachCanTra = new javax.swing.JTextField();
        txtTraLai = new javax.swing.JTextField();
        btnNhanTien = new javax.swing.JButton();
        datechooserNgayGiaoHang = new com.toedter.calendar.JDateChooser();
        btnChonKH = new javax.swing.JButton();
        lblKH = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTongGiamGia = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        btnDanhSachHD = new javax.swing.JButton();

        tableInfoKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ KHÁCH HÀNG", "TÊN KHÁCH HÀNG", "SĐT"
            }
        ));
        tableInfoKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInfoKHMouseClicked(evt);
            }
        });
        scrollInfoKH.setViewportView(tableInfoKH);

        jScrollPane5.setViewportView(listEmei);

        jLabel1.setText("TÌm Kiếm Sản Phẩm Theo Tên");

        txtSearchSP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtSearchSP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchSPCaretUpdate(evt);
            }
        });
        txtSearchSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSPActionPerformed(evt);
            }
        });

        jLabel2.setText("Phân Loại Sản Phẩm");

        cbbPhanLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Cũ" }));
        cbbPhanLoaiSP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cbbPhanLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhanLoaiSPActionPerformed(evt);
            }
        });

        btnGiam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sort_giam30.png"))); // NOI18N
        btnGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamActionPerformed(evt);
            }
        });

        btnTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sort_tang30.png"))); // NOI18N
        btnTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        panelSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelSanPham.setToolTipText("");
        panelSanPham.setName(""); // NOI18N

        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên SP", "Giá Bán", "Giỏ Hàng"
            }
        ));
        tableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSanPham);
        if (tableSanPham.getColumnModel().getColumnCount() > 0) {
            tableSanPham.getColumnModel().getColumn(0).setMinWidth(500);
            tableSanPham.getColumnModel().getColumn(1).setMinWidth(200);
            tableSanPham.getColumnModel().getColumn(2).setMinWidth(50);
        }

        jLabel17.setText("Sản Phẩm ( Nhấn Thêm để thêm sản phầm vào giỏ hàng)");

        javax.swing.GroupLayout panelSanPhamLayout = new javax.swing.GroupLayout(panelSanPham);
        panelSanPham.setLayout(panelSanPhamLayout);
        panelSanPhamLayout.setHorizontalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(panelSanPhamLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSanPhamLayout.setVerticalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSanPhamLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelDonHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Sản Phẩm", "Giá", "Sale/1SP", "SL", "Tổng Tiền", "Edit"
            }
        ));
        tableDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDonHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDonHang);
        if (tableDonHang.getColumnModel().getColumnCount() > 0) {
            tableDonHang.getColumnModel().getColumn(0).setMinWidth(250);
            tableDonHang.getColumnModel().getColumn(1).setMinWidth(130);
            tableDonHang.getColumnModel().getColumn(2).setMinWidth(90);
            tableDonHang.getColumnModel().getColumn(3).setMinWidth(30);
            tableDonHang.getColumnModel().getColumn(4).setMinWidth(130);
        }

        jLabel18.setText("Đơn hàng ( Nhấn Bỏ để xóa 1 sản phẩm ra khỏi giỏ hàng)");

        javax.swing.GroupLayout panelDonHangLayout = new javax.swing.GroupLayout(panelDonHang);
        panelDonHang.setLayout(panelDonHangLayout);
        panelDonHangLayout.setHorizontalGroup(
            panelDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDonHangLayout.createSequentialGroup()
                .addGroup(panelDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelDonHangLayout.setVerticalGroup(
            panelDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDonHangLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Khách Hàng");

        jLabel5.setText("Nhân Viên");

        jLabel6.setText("Ghi Chú");

        txtAGhiChu.setColumns(20);
        txtAGhiChu.setRows(8);
        txtAGhiChu.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane2.setViewportView(txtAGhiChu);

        jLabel7.setText("Địa chỉ nhận hàng");

        btnGDiaChiNhanHang.add(rbtnTaiCuaHang);
        rbtnTaiCuaHang.setText("Tại cửa hàng");
        rbtnTaiCuaHang.setBorder(null);
        rbtnTaiCuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTaiCuaHangActionPerformed(evt);
            }
        });

        btnGDiaChiNhanHang.add(rbtnTaiNha);
        rbtnTaiNha.setText("Tại nhà");
        rbtnTaiNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTaiNhaActionPerformed(evt);
            }
        });

        txtADiaChiNhanHang.setColumns(20);
        txtADiaChiNhanHang.setRows(8);
        txtADiaChiNhanHang.setBorder(new javax.swing.border.MatteBorder(null));
        txtADiaChiNhanHang.setEnabled(false);
        jScrollPane4.setViewportView(txtADiaChiNhanHang);

        jLabel8.setText("Phí vận chuyển");

        txtPhiVanChuyen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPhiVanChuyen.setText("0");
        txtPhiVanChuyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPhiVanChuyen.setEnabled(false);

        jLabel9.setText("Ngày giao hàng");

        jLabel10.setText("Trạng thái giao hàng");

        btnGTrangThaiGH.add(rbtnDangGiaoHang);
        rbtnDangGiaoHang.setText("Đang giao");

        btnGTrangThaiGH.add(rbtnChuaGiaoHang);
        rbtnChuaGiaoHang.setText("Chưa giao");

        btnGTrangThaiGH.add(rbtnDaGiao);
        rbtnDaGiao.setText("Đã giao");

        jLabel11.setText("Khách đưa ");

        txtKhachDua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKhachDuaFocusLost(evt);
            }
        });
        txtKhachDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachDuaActionPerformed(evt);
            }
        });

        jLabel12.setText("Chọn mã giảm giá");

        cbbChonMaGiamGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbbChonMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChonMaGiamGiaActionPerformed(evt);
            }
        });

        jLabel13.setText("Tổng tiền hàng");

        txtTongTienHang.setBackground(new java.awt.Color(60, 63, 65));
        txtTongTienHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTongTienHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTongTienHang.setEnabled(false);

        jLabel14.setText("Tổng giảm giá");

        jLabel15.setText("Khách cần trả");

        jLabel16.setText("Trả lại");

        txtKhachCanTra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtKhachCanTra.setText("0");
        txtKhachCanTra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtKhachCanTra.setEnabled(false);

        txtTraLai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTraLai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTraLai.setEnabled(false);

        btnNhanTien.setBackground(new java.awt.Color(0, 0, 204));
        btnNhanTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tiền Thối2.png"))); // NOI18N
        btnNhanTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanTienActionPerformed(evt);
            }
        });

        datechooserNgayGiaoHang.setToolTipText("");
        datechooserNgayGiaoHang.setDateFormatString("dd/MM/yyyy");

        btnChonKH.setBackground(new java.awt.Color(0, 0, 204));
        btnChonKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tìm Kiếm 1.png"))); // NOI18N
        btnChonKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonKHActionPerformed(evt);
            }
        });

        lblKH.setForeground(new java.awt.Color(255, 102, 0));
        lblKH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSDT.setForeground(new java.awt.Color(255, 102, 0));
        lblSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Số điện thoại");

        txtTongGiamGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTongGiamGia.setEnabled(false);

        txtNhanVien.setEnabled(false);
        txtNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThongTinKHLayout = new javax.swing.GroupLayout(panelThongTinKH);
        panelThongTinKH.setLayout(panelThongTinKHLayout);
        panelThongTinKHLayout.setHorizontalGroup(
            panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinKHLayout.createSequentialGroup()
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNhanVien))
                            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnDangGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnChuaGiaoHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnDaGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhiVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datechooserNgayGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelThongTinKHLayout.createSequentialGroup()
                                        .addComponent(rbtnTaiCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(rbtnTaiNha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelThongTinKHLayout.createSequentialGroup()
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinKHLayout.createSequentialGroup()
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbChonMaGiamGia, 0, 278, Short.MAX_VALUE)
                            .addComponent(txtTongTienHang)
                            .addComponent(txtKhachCanTra)
                            .addComponent(txtTraLai)
                            .addComponent(txtTongGiamGia))
                        .addGap(306, 306, 306))))
            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnNhanTien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelThongTinKHLayout.setVerticalGroup(
            panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelThongTinKHLayout.createSequentialGroup()
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelThongTinKHLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinKHLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnTaiCuaHang)
                        .addComponent(rbtnTaiNha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelThongTinKHLayout.createSequentialGroup()
                        .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhiVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(datechooserNgayGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnDangGiaoHang)
                    .addComponent(rbtnChuaGiaoHang)
                    .addComponent(rbtnDaGiao)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbChonMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTienHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKhachCanTra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtTraLai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhanTien, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        datechooserNgayGiaoHang.getAccessibleContext().setAccessibleName("");

        btnDanhSachHD.setBackground(new java.awt.Color(0, 0, 204));
        btnDanhSachHD.setText("Danh Sách Hóa Đơn");
        btnDanhSachHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbPhanLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170)
                        .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDanhSachHD, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelThongTinKH, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDanhSachHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbbPhanLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelThongTinKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelSanPham.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTaiCuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTaiCuaHangActionPerformed
        txtADiaChiNhanHang.setText("Tại cửa hàng");
        txtADiaChiNhanHang.setEnabled(false);
        txtPhiVanChuyen.setText("0");
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        datechooserNgayGiaoHang.setDate(date);
        //datechooserNgayGiaoHang=date;
        rbtnDaGiao.setSelected(true);
        rbtnDangGiaoHang.setVisible(false);
        rbtnChuaGiaoHang.setVisible(false);

    }//GEN-LAST:event_rbtnTaiCuaHangActionPerformed

    private void btnNhanTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanTienActionPerformed

//        if(!rbtnTaiNha.isSelected() && !rbtnTaiCuaHang.isSelected()) {
//            JOptionPane.showMessageDialog(panelSanPham, "Chưa chọn địa điểm nhận hàng!", "Hệ thống của hàng điện thoại TNT", JOptionPane.ERROR_MESSAGE);
//        }
//        if (txtKhachDua == "") {
//            JOptionPane.showMessageDialog(panelSanPham, "Khách chưa đưa tiền!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
//        } else if (rbtnTaiNha.isSelected() && (Integer.parseInt(txtKhachDua.getText()) < Integer.parseInt(txtKhachCanTra.getText()) + 100000)) {
//            JOptionPane.showMessageDialog(panelSanPham, "Tổng tiền phải bao gồm tiền ship!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
//        }
        if (!txtKhachDua.getText().equals("") && !txtKhachCanTra.getText().equals("") && txtKhachDua.getText().compareTo(txtKhachCanTra.getText()) == 1) {
            txtTraLai.setText(String.valueOf(Integer.parseInt(txtKhachDua.getText()) - Integer.parseInt(txtKhachCanTra.getText())));
        } else {
            txtTraLai.setText("0 ");
        }
        int flag = 0;
        if (lblKH.getText().equals("")) {
            flag = 0;
            JOptionPane.showMessageDialog(panelSanPham, "THông tin Khách Hàng đang trống!", "Hệ thống của hàng điện thoại TNT", JOptionPane.ERROR_MESSAGE);
        } else {
            flag = 1;
        }
        if (!rbtnTaiNha.isSelected() && !rbtnTaiCuaHang.isSelected()) {
            flag = 0;
            JOptionPane.showMessageDialog(panelSanPham, "Chưa chọn địa điểm nhận hàng!", "Hệ thống của hàng điện thoại TNT", JOptionPane.ERROR_MESSAGE);
        } else {
            flag = 1;
        }

        if (!rbtnDangGiaoHang.isSelected() && !rbtnChuaGiaoHang.isSelected() && !rbtnDaGiao.isSelected()) {
            flag = 0;
            JOptionPane.showMessageDialog(panelSanPham, "Chưa xác định trạng thái giao hàng!", "Hệ thống của hàng điện thoại TNT", JOptionPane.ERROR_MESSAGE);
        } else {
            flag = 1;
        }
        if (txtTongTienHang.getText().equals("")) {
            flag = 0;
            JOptionPane.showMessageDialog(panelSanPham, "Chưa có sản phẩm trong đơn hàng!", "Hệ thống của hàng điện thoại TNT", JOptionPane.ERROR_MESSAGE);

        } else {
            flag = 1;
        }
        if (txtKhachDua.getText().equals("")) {
            flag = 0;
            JOptionPane.showMessageDialog(panelSanPham, "Số tiền khách đưa đang bị để trống!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
            //txtKhachDua.requestFocus();
        } //        else if (rbtnTaiNha.isSelected() && !txtTongTienHang.getText().equals("")&&(Integer.parseInt(txtKhachDua.getText()) < Integer.parseInt(txtKhachCanTra.getText()) + 100000)) {
        //            JOptionPane.showMessageDialog(panelSanPham, "Khách cần trả thêm tiền ship!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
        //        flag =0;
        //        txtKhachDua.requestFocus();
        //        }
        else {
            if (!txtTongTienHang.getText().equals("")) {
                if (rbtnTaiNha.isSelected()) {
                    if (Integer.parseInt(txtKhachDua.getText()) < Integer.parseInt(txtKhachCanTra.getText()) + 100000) {
                        flag = 0;
                        JOptionPane.showMessageDialog(panelSanPham, "Khách chưa thanh toán đủ tiền!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
                        //txtKhachCanTra.requestFocus();
                    }
                } else if (rbtnTaiCuaHang.isSelected()) {
                    if (Integer.parseInt(txtKhachDua.getText()) < Integer.parseInt(txtKhachCanTra.getText())) {
                        flag = 0;
                        JOptionPane.showMessageDialog(panelSanPham, "Khách chưa thanh toán đủ tiền!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
                        //txtKhachCanTra.requestFocus();
                    }
                }
            }
        }
        if (flag == 1) {
            int x = JOptionPane.showConfirmDialog(panelSanPham, "Bạn có muốn thanh toán hóa đơn không? ", "Hệ thống của hàng điện thoại TNT", JOptionPane.YES_NO_OPTION);
            if (x == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(panelSanPham, "Thanh toán thành công!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
                int y = JOptionPane.showConfirmDialog(panelSanPham, "Bạn có muốn in hóa đơn không?", "Hệ thống của hàng điện thoại TNT", JOptionPane.YES_NO_OPTION);
                if (y == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(panelSanPham, "In hóa đơn thành công!", "Hệ thống của hàng điện thoại TNT", JOptionPane.INFORMATION_MESSAGE);
                    String diachinhanhang = "Tại cửa hàng";
                    if (rbtnTaiNha.isSelected()) {
                        diachinhanhang = "Tại nhà";
                        txtKhachCanTra.setText(String.valueOf(Integer.parseInt(txtKhachCanTra.getText()) + 100000));
                    }
                    txtTongGiamGia.setText(String.valueOf(Integer.parseInt(txtTongTienHang.getText()) - Integer.parseInt(txtKhachCanTra.getText())));
                    for (int i = 0; i < list_soseri.size(); i++) {
                        boolean add_pbh = d.add_PBH(list_soseri.get(i), lblSDT.getText());
                    }

                    for (int i = 0; i < list_soseri.size(); i++) {
                        boolean update_tt_emei = d.edit_trangthai_inEmei(list_soseri.get(i), "2");
                        boolean update_tt_of_pbh = d.update_tt_of_PBH(list_soseri.get(i), "2");
                        boolean add_doi_tra = d.add_Doi_Tra(list_soseri.get(i));
                    }
                    list_soseri.removeAll(list_soseri);
                    String mggkh = (String) cbbChonMaGiamGia.getSelectedItem();
                    boolean inhd = d.add_HD(lblSDT.getText(), txtTongTienHang.getText(), txtPhiVanChuyen.getText(), txtTongGiamGia.getText(), txtKhachCanTra.getText(), mggkh);

                    String sdt = lblSDT.getText();
//                    Calendar cal = Calendar.getInstance();
//                    Date date = cal.getTime();
//                    java.sql.Date ngaylaphd = new java.sql.Date(date.getTime());
                    for (int i = 0; i < tableDonHang.getRowCount(); i++) {
                        String tensp = (String) tableDonHang.getValueAt(i, 0);
                        int soluong = (int) tableDonHang.getValueAt(i, 3);
                        int dongia = (int) tableDonHang.getValueAt(i, 1);
                        String sale = (String) tableDonHang.getValueAt(i, 2);
                        boolean cthd = d.add_CT_HD(tensp, sdt, soluong, dongia, sale);
                        
                    }
                    d.add_Hoa_Don_Tmp(lblKH.getText(), lblSDT.getText(), txtTongTienHang.getText(), txtPhiVanChuyen.getText(), txtTongGiamGia.getText(), txtKhachCanTra.getText());
                    try {
                        try {
                            chucNangKhac.Fill_to_HoaDon(datechooserNgayGiaoHang, lblKH, lblSDT, diachinhanhang, tableDonHang, txtTongTienHang, txtPhiVanChuyen, txtTongGiamGia, txtKhachCanTra, txtKhachDua, txtTraLai, txtNhanVien);
                        } catch (IOException ex) {
                            //Logger.getLogger(Ban_Hang.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (DocumentException ex) {
                        //Logger.getLogger(Ban_Hang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    DefaultTableModel model = (DefaultTableModel) tableDonHang.getModel();
                    for (int i = tableDonHang.getRowCount() - 1; i >= 0; i--) {
                        model.removeRow(i);
                    }

                    
                    
                    //btnInBill.setEnabled(true);
                    
                    lblKH.setText("");
                    lblSDT.setText("");
                    btnGDiaChiNhanHang.clearSelection();
                    txtAGhiChu.setText("");
                    txtADiaChiNhanHang.setText("");
                    txtPhiVanChuyen.setText("0");
                    btnGTrangThaiGH.clearSelection();
                    txtKhachDua.setText("");
                    txtTongTienHang.setText("0");
                    tong_tien_hang = 0;
                    txtTongGiamGia.setText("0");
                    txtKhachCanTra.setText("0");
                    tien_khach_can_tra = 0;
                    txtTraLai.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnNhanTienActionPerformed

    private void rbtnTaiNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTaiNhaActionPerformed
        txtADiaChiNhanHang.setEnabled(true);
        txtADiaChiNhanHang.setText("");
        txtADiaChiNhanHang.getText();
        txtPhiVanChuyen.setText("100000");
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        datechooserNgayGiaoHang.setDate(date);
        btnGTrangThaiGH.clearSelection();
        rbtnDangGiaoHang.setVisible(true);
        rbtnChuaGiaoHang.setVisible(true);
        rbtnDaGiao.setVisible(false);
    }//GEN-LAST:event_rbtnTaiNhaActionPerformed

    private void txtKhachDuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKhachDuaFocusLost
        check.check_So(txtKhachDua);
    }//GEN-LAST:event_txtKhachDuaFocusLost

    private void txtSearchSPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchSPCaretUpdate
        d.LoadTable_GoiYSP(tableSanPham, txtSearchSP);

    }//GEN-LAST:event_txtSearchSPCaretUpdate
    static int tong_tien_hang = 0;
    static int tien_khach_can_tra = 0;
    static ArrayList<String> list_soseri = new ArrayList<>();
//    static int set_row_table_DonHang = 0;           // biến static để xóa row 0
//    static int flag_tmp = 0;
    private void tableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSanPhamMouseClicked
        int col = tableSanPham.columnAtPoint(evt.getPoint());
        int row = tableSanPham.rowAtPoint(evt.getPoint());
        if (col == 2) {
            tong_tien_hang += (int) tableSanPham.getValueAt(row, 1);
        }
        txtTongTienHang.setText(String.valueOf(tong_tien_hang));
        txtKhachCanTra.setText(String.valueOf(tong_tien_hang));
//        if (col == 2) {
//            d.Load_to_DonHang(col, row, tableSanPham, tableDonHang);
//        }
        if (col == 2) {
            String tensp = (String) tableSanPham.getValueAt(row, 0);
            JComboBox cbb = new JComboBox();
//            for (int i = 0; i < list.size(); i++) {
//                cbb.addItem(list);
//            }
            cbb = d.get_Emei(tensp, cbb);
            int input = JOptionPane.showConfirmDialog(null, cbb, "Chọn Emei cho sản phẩm", JOptionPane.DEFAULT_OPTION);
            if (input == JOptionPane.OK_OPTION) {
                d.Load_to_DonHang(col, row, tableSanPham, tableDonHang);
                String soseri = (String) cbb.getSelectedItem();
                list_soseri.add(soseri);
//                boolean b = d.add_PBH(soseri);
                boolean c = d.edit_trangthai_inEmei(soseri, "0");
            }
        }
    }//GEN-LAST:event_tableSanPhamMouseClicked

    private void btnDanhSachHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachHDActionPerformed
        // chucNangKhac.Print_row(tableSanPham);
    }//GEN-LAST:event_btnDanhSachHDActionPerformed
    //static int tien_ship = 0;
    static int tong_tien = 0;
    private void tableDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDonHangMouseClicked
//        if (rbtnTaiNha.isSelected()) {
//            tien_ship = 100000;
//        } else {
//            tien_ship = 0;
//        }
        int col = tableDonHang.columnAtPoint(evt.getPoint());
        int row = tableDonHang.getSelectedRow();

//        int tong_tien =0;
        //int tmp_tongtien = Integer.parseInt(txtTongTienHang.getText());
        tong_tien = tong_tien_hang;
        //String tmp = "0 percent"; // giá trị đc chọn của cbb
        if (col == 2) {
            JComboBox cbb = new JComboBox();
            cbb = d.Show_MaGG_TheoSP(col, row, tableDonHang);
            int input = JOptionPane.showConfirmDialog(null, cbb, "Chọn Mã Giảm Giá cho sản phẩm", JOptionPane.DEFAULT_OPTION);
            if (input == JOptionPane.OK_OPTION) {
                tableDonHang.setValueAt("0 percent", row, col);
                String tmp = "";
                if (cbb.getItemAt(0) == null) {
                    tmp = "0 percent";
                } else {
                    tmp = (String) cbb.getSelectedItem();
                }
                tableDonHang.setValueAt(tmp, row, col);

//                String tmpString = (String) tableDonHang.getValueAt(row, col);   
            }
        }
        for (int j = 0; j < tableDonHang.getRowCount(); j++) {
            String tmp = (String) tableDonHang.getValueAt(j, 2);
            int tmp2 = 0;
            String check_kituString = "VND"; // tmp = 100vnd
            
            if (tmp.contains(check_kituString)) {
                for (int i = 0; i < tmp.length() - 3; i++) {
                    tmp2 = tmp2 * 10 + Integer.parseInt(String.valueOf(tmp.charAt(i)));
                }
            } else {
                for (int i = 0; i < tmp.length() - 8; i++) {
                    tmp2 = tmp2 * 10 + Integer.parseInt(String.valueOf(tmp.charAt(i)));
                }
            }
            int sl = (int) tableDonHang.getValueAt(j, 3);
//            int thanhtien = (int) tableDonHang.getValueAt(row, 4)-(((int) tableDonHang.getValueAt(row, 4)*tmp2)/100);
//            tableDonHang.setValueAt(thanhtien, row, 4);
            if (tmp2 <= 100) {
                tong_tien = tong_tien - (((int) tableDonHang.getValueAt(j, 4) * tmp2) / 100);
            } else {
                tong_tien = tong_tien - tmp2 * sl;
            }
            txtKhachCanTra.setText(String.valueOf(tong_tien));
            // tong_tien = tong_tien_hang;
        }
        String tensp = "";
        if (col == 5) {
            tong_tien_hang -= (int) tableDonHang.getValueAt(row, 1);
            txtTongTienHang.setText(String.valueOf(tong_tien_hang));
            tableDonHang.setValueAt((int) tableDonHang.getValueAt(row, 4) - (int) tableDonHang.getValueAt(row, 1), row, 4);
            tong_tien -= (int) tableDonHang.getValueAt(row, 1);
            String tmp = (String) tableDonHang.getValueAt(row, 2);
            int tmp2 = 0;
            String check_kituString = "VND"; // tmp = 100vnd
            
            if (tmp.contains(check_kituString)) {
                for (int i = 0; i < tmp.length() - 3; i++) {
                    tmp2 = tmp2 * 10 + Integer.parseInt(String.valueOf(tmp.charAt(i)));
                }
            } else {
                for (int i = 0; i < tmp.length() - 8; i++) {
                    tmp2 = tmp2 * 10 + Integer.parseInt(String.valueOf(tmp.charAt(i)));
                }
            }
            tong_tien += ((int) tableDonHang.getValueAt(row, 1) * tmp2 / 100);
            txtKhachCanTra.setText(String.valueOf(tong_tien));
            int soluong = (int) tableDonHang.getValueAt(row, 3);
            if (soluong > 1) {
                soluong--;
                tableDonHang.setValueAt(soluong, row, 3);
                tensp = (String) tableDonHang.getValueAt(row, 0);
            } else {
                tensp = (String) tableDonHang.getValueAt(row, 0);
                ((DefaultTableModel) tableDonHang.getModel()).removeRow(row);
            }
            // update lại số seri sau khi xóa khỏi giỏ hàng
//            String tensp = (String) tableDonHang.getValueAt(row, 0);
            ArrayList<String> list_emei_tt0_in_emei = d.get_soseri(tensp);
            int flag = 0;
            for (int i = 0; i < list_emei_tt0_in_emei.size(); i++) {
                for (int j = 0; j < list_soseri.size(); j++) {
                    if (list_emei_tt0_in_emei.get(i).equals(list_soseri.get(j))) {
                        boolean edit = d.edit_trangthai_inEmei(list_emei_tt0_in_emei.get(i), "1");
                        list_soseri.remove(list_soseri.get(j));
                        //list_emei_tt0_in_emei.remove(list_emei_tt0_in_emei.get(i));
//                        boolean delete = d.delete_baohanh(list_emei_tt0_in_emei.get(i));
                        flag = 1;
                        break;
                    }
                }
                if (flag == 1) {
                    break;
                }
            }
//            for(int i=0;i<list_emei_tt0_in_emei.size();i++)
//            {
//                System.out.println(list_emei_tt0_in_emei.get(i)+"@@");
//            }
//System.out.println(tensp+" --");

        }
    }//GEN-LAST:event_tableDonHangMouseClicked

    private void btnChonKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonKHActionPerformed
        jPopupMenu1.show(this, 580, 150);
    }//GEN-LAST:event_btnChonKHActionPerformed

    private void tableInfoKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInfoKHMouseClicked
        int row = tableInfoKH.getSelectedRow();
        d.Load_to_lable_InfoKH(lblKH, lblSDT, tableInfoKH, row);
        d.Load_to_CBBMGG_of_KH(tableInfoKH, cbbChonMaGiamGia, row);
        jPopupMenu1.setVisible(false);
    }//GEN-LAST:event_tableInfoKHMouseClicked

    private void cbbChonMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChonMaGiamGiaActionPerformed
        JComboBox cbb = new JComboBox();
        cbb = cbbChonMaGiamGia;
        //int tong_tien2 =0;
        String mggkh = (String) cbb.getSelectedItem();
        if (mggkh != null) {
            txtKhachCanTra.setText(String.valueOf(tong_tien));
            int tong_tien1 = Integer.parseInt(txtKhachCanTra.getText());
            //tong_tien2 = tong_tien1;
            int tmp2 = 0;
            String check_kituString = "VND";
            if (mggkh.contains(check_kituString)) {
                for (int i = 0; i < mggkh.length() - 4; i++) {
                    tmp2 = tmp2 * 10 + Integer.parseInt(String.valueOf(mggkh.charAt(i)));
                }
            } else {
                for (int i = 0; i < mggkh.length() - 8; i++) {
                    tmp2 = tmp2 * 10 + Integer.parseInt(String.valueOf(mggkh.charAt(i)));
                }
            }
            if (tong_tien1 == 0) {
                return;
            } else {
                if (tmp2 <= 100) {
                    tong_tien1 = tong_tien1 - ((tong_tien1 * tmp2) / 100);
                } else {
                    tong_tien1 = tong_tien1 - tmp2;
                }
            }
            txtKhachCanTra.setText(String.valueOf(tong_tien1));
            //tong_tien1=tong_tien2;  
        }
    }//GEN-LAST:event_cbbChonMaGiamGiaActionPerformed

    private void txtKhachDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachDuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachDuaActionPerformed

    private void txtSearchSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSPActionPerformed

    private void btnGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamActionPerformed
        ArrayList<SanPham> list_sp = d.getSPModel((String) cbbPhanLoaiSP.getSelectedItem());
        chucNangKhac.SapXepGiamTheoGia(list_sp);
        DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
        model.setRowCount(0);
        for (int i = 0; i < list_sp.size(); i++) {
            model.addRow(new Object[]{
                list_sp.get(i).getTenSp(), list_sp.get(i).getGia(), "Thêm"
            });
        }
        model.fireTableDataChanged();
    }//GEN-LAST:event_btnGiamActionPerformed

    private void btnTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangActionPerformed
        ArrayList<SanPham> list_sp = d.getSPModel((String) cbbPhanLoaiSP.getSelectedItem());
        chucNangKhac.SapXepTangTheoGia(list_sp);
        DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
        model.setRowCount(0);
        for (int i = 0; i < list_sp.size(); i++) {
            model.addRow(new Object[]{
                list_sp.get(i).getTenSp(), list_sp.get(i).getGia(), "Thêm"
            });
        }
        model.fireTableDataChanged();
    }//GEN-LAST:event_btnTangActionPerformed

    private void cbbPhanLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhanLoaiSPActionPerformed
        String loai = (String) cbbPhanLoaiSP.getSelectedItem();
        d.LoadTable_SP(tableSanPham, loai);
    }//GEN-LAST:event_cbbPhanLoaiSPActionPerformed

    private void txtNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhanVienActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hoa_Don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ban_Hang().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonKH;
    private javax.swing.JButton btnDanhSachHD;
    private javax.swing.ButtonGroup btnGDiaChiNhanHang;
    private javax.swing.ButtonGroup btnGTrangThaiGH;
    private javax.swing.JButton btnGiam;
    private javax.swing.JButton btnNhanTien;
    private javax.swing.JButton btnTang;
    private javax.swing.JComboBox<String> cbbChonMaGiamGia;
    private javax.swing.JComboBox<String> cbbPhanLoaiSP;
    private com.toedter.calendar.JDateChooser datechooserNgayGiaoHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JList<String> listEmei;
    private javax.swing.JPanel panelDonHang;
    private javax.swing.JPanel panelSanPham;
    private javax.swing.JPanel panelThongTinKH;
    private javax.swing.JRadioButton rbtnChuaGiaoHang;
    private javax.swing.JRadioButton rbtnDaGiao;
    private javax.swing.JRadioButton rbtnDangGiaoHang;
    private javax.swing.JRadioButton rbtnTaiCuaHang;
    private javax.swing.JRadioButton rbtnTaiNha;
    private javax.swing.JScrollPane scrollInfoKH;
    private javax.swing.JTable tableDonHang;
    private javax.swing.JTable tableInfoKH;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextArea txtADiaChiNhanHang;
    private javax.swing.JTextArea txtAGhiChu;
    private javax.swing.JTextField txtKhachCanTra;
    private javax.swing.JTextField txtKhachDua;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtPhiVanChuyen;
    private javax.swing.JTextField txtSearchSP;
    private javax.swing.JTextField txtTongGiamGia;
    private javax.swing.JTextField txtTongTienHang;
    private javax.swing.JTextField txtTraLai;
    // End of variables declaration//GEN-END:variables
}
