/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BanHang_HoaDon;

import BanHang_HoaDon.NhanVienDAO;
//import DAO.ThongKeDao;
import BanHang_HoaDon.ThongKeDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS
 */
public class PanelThongKe extends javax.swing.JPanel {

    ThongKeDao thongKeDao = new ThongKeDao();
    public PanelThongKe() throws Exception {
        initComponents();
        showBarChart();
    }
    
    public int loiNhuanThang(int thang) throws Exception{
        ArrayList<String>list=thongKeDao.getSoHDchoThang(thang);
        int sum=0;
        for (String soHD : list) {
            
            sum+=thongKeDao.getLoiNhuanTheoHoaDon(soHD);
            System.out.println(soHD+":"+thongKeDao.getLoiNhuanTheoHoaDon(soHD));
        }
        return sum;
        
    }
     public void showBarChart() throws Exception{
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(loiNhuanThang(1), "Amount", "T1");
        dataset.setValue(loiNhuanThang(2), "Amount", "T2");
        dataset.setValue(loiNhuanThang(3), "Amount", "T3");
        dataset.setValue(loiNhuanThang(4), "Amount", "T4");
        dataset.setValue(loiNhuanThang(5), "Amount", "T5");
        dataset.setValue(loiNhuanThang(6), "Amount", "T6");
        dataset.setValue(loiNhuanThang(7), "Amount", "T7");
        dataset.setValue(loiNhuanThang(8), "Amount", "T8");
        dataset.setValue(loiNhuanThang(9), "Amount", "T9");
        dataset.setValue(loiNhuanThang(10), "Amount", "T10");
        dataset.setValue(loiNhuanThang(11), "Amount", "T11");
        dataset.setValue(loiNhuanThang(12), "Amount", "T12");
        
        JFreeChart chart = ChartFactory.createBarChart("contribution","Tháng","Tiền", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        //categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(204,0,51);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        pnlBieuDo.removeAll();
        pnlBieuDo.add(barpChartPanel, BorderLayout.CENTER);
        pnlBieuDo.validate();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlBieuDo = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlBieuDo.setLayout(new javax.swing.BoxLayout(pnlBieuDo, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addGap(38, 38, 38))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlBieuDo;
    // End of variables declaration//GEN-END:variables
}
